language: go
go_import_path: github.com/renaynay/go-hobbits
sudo: false
env:
  - GOPATH=/home/travis/gopath

os: osx
dist: xenial
sudo: required
go: 1.12.x

install:
  - go get -u golang.org/x/lint/golint

jobs:
  include:
    - script: golint ./...
    - script: go vet ./...
    - script: go test ./...